name: Example install of Ruby 2.7.6

on: 
  push:
    paths:
      - '_config.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.6' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake
    - name: Print version
      run: ${{ steps.ruby.outputs.ruby-path }} --version
    - name: Update projects
      run: ruby update-and-preprocess.rb
